# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_constr.xdc

# Block Designs: bd/vga_ctrl_block/vga_ctrl_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_ctrl_block || ORIG_REF_NAME==vga_ctrl_block} -quiet] -quiet

# IP: bd/vga_ctrl_block/ip/vga_ctrl_block_clk_wiz_0_0/vga_ctrl_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_ctrl_block_clk_wiz_0_0 || ORIG_REF_NAME==vga_ctrl_block_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/user/Desktop/Personal_Stuff/Homework/an4/PRACTICA_CAPGEMINI/vga_ctrl/vga_ctrl.gen/sources_1/bd/vga_ctrl_block/vga_ctrl_block_ooc.xdc
